apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}